### ISSUE TITLE
The main page has the login for all the three users of the system. it should be changed to different pages

### ISSUE THREAD

**Issue by arushnagpal** [thapar-technovators/iap_thapar#1]
@akshitarora  @chahak  @abhi017

**Comment by abhinavgargin** [comment]
Yes they should be done like the existing IAP. Because the person bothering about faculty login won't bother about the student login.

**Comment by arushnagpal** [comment]
Okay Cool. Lets change it then

**Comment by arushnagpal** [comment]
Done
